---
- name: Backup current Netplan configuration
  ansible.builtin.copy:
    src: "{{ network_netplan_file }}"
    dest: "{{ network_netplan_file }}.before-ansible"
    remote_src: true
    owner: root
    group: root
    mode: "0600"
    force: false

- name: Deploy Netplan configuration
  ansible.builtin.template:
    src: 50-cloud-init.yaml.j2
    dest: "{{ network_netplan_file }}"
    owner: root
    group: root
    mode: "0600"
    backup: true
  notify: Apply Netplan

- name: Validate Netplan configuration
  ansible.builtin.command:
    cmd: netplan generate
  changed_when: false
