---
nextcloud_enabled: false
nextcloud_app_dir: "{{ platform_apps_root }}/nextcloud"
nextcloud_data_dir: "{{ platform_data_root }}/nextcloud"
nextcloud_container_name: nextcloud
nextcloud_storage_owner: "{{ platform_admin_user }}"
nextcloud_storage_group: "{{ platform_admin_user }}"

nextcloud_image: nextcloud:35.0.0-apache
nextcloud_container_uid: 33
nextcloud_container_gid: 33
nextcloud_hostname: "nextcloud.{{ platform_domain }}"
nextcloud_protocol: https
nextcloud_trusted_proxy: "{{ platform_proxy_network }}"
nextcloud_network_proxy: "{{ platform_proxy_network }}"
traefik_tls_mode: internal
traefik_acme_resolver: letsencrypt
