---
docker_apt_keyring_dir: "/etc/apt/keyrings"

docker_apt_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_apt_key_path: "/etc/apt/keyrings/docker.asc"

docker_apt_repository_url: "https://download.docker.com/linux/ubuntu"
docker_apt_repository_file: "/etc/apt/sources.list.d/docker.list"

docker_architecture_map:
  x86_64: amd64
  aarch64: arm64
  
container_runtime_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

container_runtime_docker_users: []

docker_log_driver: json-file
docker_log_max_size: 10m
docker_log_max_file: 3
docker_live_restore: true
