---
storage_root: "{{ platform_root }}"
storage_directories:
  - apps
  - data
  - backups

storage_owner: "{{ platform_admin_user }}"
storage_group: "{{ platform_admin_user }}"

storage_directory_mode: "0755"
storage_backup_mode: "0700"
