---
system_update_cache_valid_time: 3600
system_update_upgrade_type: safe

system_update_autoremove: false
system_update_autoremove_purge: false
system_update_autoclean: true

system_update_reboot_enabled: false
system_update_reboot_timeout: 600
